import type { Metadata } from "next";
import { Kanit, Geist } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const kanit = Kanit({ 
  subsets: ['latin'],
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900']

 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={cn("font-sans", geist.variable)}>
      
      <body className={kanit.className}>


        {children}
        <BootstrapClient/>
        </body>
    </html>
  );
}
