import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "@/components/BootstrapClient";
import Navbars from "@/components/Navbars/Navbars";
import "./globals.css";
import Loadings from '@/components/LoadingScreen/Loading';

const kanit = Kanit({ 
  subsets: ['latin'],
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900']

 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      
      <body className={kanit.className}>
        <Loadings/>
        <Navbars/>
        {children}
        <BootstrapClient/>
        </body>
    </html>
  );
}
